services:
    news-aggregator-app:
        container_name: news-aggregator-app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - news-aggregator-db
        networks:
            - app_network

    news-aggregator-nginx:
        container_name: news-aggregator-nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 80:80
        depends_on:
            - news-aggregator-app
        environment:
            NGINX_FPM_HOST: news-aggregator-app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network

    news-aggregator-db:
        container_name: news-aggregator-db
        image: mysql:latest
        restart: always
        volumes:
            - ./storage/db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: news_aggregator
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
